version: '3.8'

services:
  app:
    image: teetony/learning-app:v1.0
    ports:
      - "3001:3001"
    environment:
      JWT_SECRET: "${JWT_SECRET}"
      DATABASE_URL: "${DATABASE_URL}"
    env_file:
      - .env
